Repository 9haTeam/9pang, pull requests merged in 2025-03, with the labels that each got.

#29 Feature/order/crud
  order/Dockerfile
  order/build.gradle
  order/docker-compose.yml
  order/settings.gradle
  order/src/main/java/com/_hateam/order/OrderApplication.java
  order/src/main/java/com/_hateam/order/application/dto/OrderRequestDto.java
  order/src/main/java/com/_hateam/order/application/dto/OrderResponseDto.java
  order/src/main/java/com/_hateam/order/application/dto/OrderSearchDto.java
  order/src/main/java/com/_hateam/order/application/dto/OrderUpdateDto.java
  order/src/main/java/com/_hateam/order/application/service/OrderService.java
  order/src/main/java/com/_hateam/order/domain/model/Order.java
  order/src/main/java/com/_hateam/order/domain/model/OrderProduct.java
  order/src/main/java/com/_hateam/order/domain/model/OrderStatus.java
  order/src/main/java/com/_hateam/order/domain/repository/OrderProductRepository.java
  order/src/main/java/com/_hateam/order/domain/repository/OrderRepository.java
  order/src/main/java/com/_hateam/order/domain/service/OrderDomainService.java
  order/src/main/java/com/_hateam/order/infrastructure/configuration/SecurityConfig.java
  order/src/main/java/com/_hateam/order/infrastructure/configuration/SwaggerConfig.java
  order/src/main/java/com/_hateam/order/infrastructure/repository/JpaOrderProductRepository.java
  order/src/main/java/com/_hateam/order/infrastructure/repository/JpaOrderRepository.java
  order/src/main/java/com/_hateam/order/infrastructure/repository/OrderProductRepositoryImpl.java
  order/src/main/java/com/_hateam/order/infrastructure/repository/OrderRepositoryImpl.java
  order/src/main/java/com/_hateam/order/presentation/controller/OrderController.java
  order/src/main/resources/application.properties
Labels: documentation, enhancement

#32 Feature/hub route/crud
  .idea/9pang.iml
  .idea/misc.xml
  hub/hub-route/src/main/java/com/_hateam/dto/HubRouteDto.java
  hub/hub-route/src/main/java/com/_hateam/dto/HubRouteRequestDto.java
  hub/hub-route/src/main/java/com/_hateam/entity/HubRoute.java
  hub/hub-route/src/main/java/com/_hateam/hub_route/HubRouteApplication.java
  hub/hub-route/src/main/java/com/_hateam/service/HubRouteService.java
  hub/hub/build.gradle
  hub/hub/src/main/java/com/_hateam/HubApplication.java
  hub/hub/src/main/java/com/_hateam/controller/HubController.java
  hub/hub/src/main/java/com/_hateam/controller/HubRouteController.java
  hub/hub/src/main/java/com/_hateam/dto/HubRouteDto.java
  hub/hub/src/main/java/com/_hateam/dto/HubRouteRequestDto.java
  hub/hub/src/main/java/com/_hateam/entity/Hub.java
  hub/hub/src/main/java/com/_hateam/entity/HubRoute.java
  hub/hub/src/main/java/com/_hateam/global/dto/CreatedInfo.java
  hub/hub/src/main/java/com/_hateam/global/dto/ResponseDto.java
  hub/hub/src/main/java/com/_hateam/global/entity/Timestamped.java
  hub/hub/src/main/java/com/_hateam/global/exception/CustomAccessDeniedException.java
  hub/hub/src/main/java/com/_hateam/global/exception/CustomAccessDeniedHandler.java
  hub/hub/src/main/java/com/_hateam/global/exception/CustomConflictException.java
  hub/hub/src/main/java/com/_hateam/global/exception/CustomForbiddenException.java
  hub/hub/src/main/java/com/_hateam/global/exception/CustomNotFoundException.java
  hub/hub/src/main/java/com/_hateam/global/exception/ExceptionResponse.java
  hub/hub/src/main/java/com/_hateam/global/exception/GlobalExceptionHandler.java
  hub/hub/src/main/java/com/_hateam/repository/HubRepository.java
  hub/hub/src/main/java/com/_hateam/repository/HubRouteRepository.java
  hub/hub/src/main/java/com/_hateam/service/HubRouteService.java
  hub/hub/src/main/java/com/_hateam/service/HubService.java
  hub/hub/src/main/resources/application.properties
Labels: enhancement

#40 Feature/company/crud
  .idea/9pang.iml
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/gateway.main.iml
  company/Dockerfile
  company/HELP.md
  company/build.gradle
  company/company/build.gradle
  company/company/gradlew.bat
  company/company/src/main/java/com/_hateam/company/CompanyApplication.java
  company/company/src/main/resources/application.properties
  company/gradle/wrapper/gradle-wrapper.jar
  company/gradle/wrapper/gradle-wrapper.properties
  company/gradlew
  company/gradlew.bat
  company/product/HELP.md
  company/product/build.gradle
  company/product/gradle/wrapper/gradle-wrapper.jar
  company/product/gradle/wrapper/gradle-wrapper.properties
  company/product/gradlew
  company/product/gradlew.bat
  company/product/settings.gradle
  company/product/src/main/java/com/_hateam/product/ProductApplication.java
  company/product/src/main/resources/application.properties
  company/product/src/test/java/com/_hateam/product/ProductApplicationTests.java
  company/settings.gradle
  company/src/main/java/com/_hateam/CompanyApplication.java
  company/src/main/java/com/_hateam/CompanyType.java
  company/src/main/java/com/_hateam/controller/CompanyController.java
  company/src/main/java/com/_hateam/controller/ProductController.java
  company/src/main/java/com/_hateam/dto/CompanyDto.java
  company/src/main/java/com/_hateam/dto/CompanyRequestDto.java
  company/src/main/java/com/_hateam/dto/ProductDto.java
  company/src/main/java/com/_hateam/dto/ProductRequestDto.java
  company/src/main/java/com/_hateam/entity/Company.java
  company/src/main/java/com/_hateam/entity/Product.java
  company/src/main/java/com/_hateam/repository/CompanyRepository.java
  company/src/main/java/com/_hateam/repository/ProductRepository.java
  company/src/main/java/com/_hateam/service/CompanyService.java
  company/src/main/java/com/_hateam/service/ProductService.java
  company/src/main/resources/application.properties
  company/src/test/java/com/_hateam/company/CompanyApplicationTests.java
  hub/hub-route/HELP.md
  hub/hub/src/main/resources/application.properties
Labels: enhancement

#42 Feature/hub/cache
  .idea/compiler.xml
  .idea/modules.xml
  common/build.gradle
  common/src/main/java/com/_hateam/common/config/RedisConfig.java
  common/src/main/java/com/_hateam/common/controller/RedisCacheController.java
  common/src/main/resources/application.properties
  hub/hub/src/main/java/com/_hateam/service/HubService.java
Labels: enhancement

#48 fix: gitignore 정리
  .idea/dataSources.xml
  .idea/encodings.xml
  .idea/modules/9pang.iml
  .idea/modules/common.main.iml
  .idea/modules/common.test.iml
  .idea/modules/company.main.iml
  .idea/modules/deliver-user.iml
  .idea/modules/deliver-user.main.iml
  .idea/modules/deliver-user.test.iml
  .idea/modules/eureka.main.iml
  .idea/modules/gateway.main.iml
  .idea/modules/gateway.test.iml
  .idea/modules/hub-route.iml
  .idea/modules/hub-route.test.iml
  .idea/modules/hub.main.iml
  .idea/modules/hub.test.iml
  .idea/modules/message.iml
  .idea/modules/message.main.iml
  .idea/modules/message.test.iml
  .idea/modules/order.main.iml
  .idea/modules/order.test.iml
  .idea/modules/product.iml
  .idea/modules/product.main.iml
  .idea/modules/product.test.iml
  .idea/modules/server.iml
  .idea/modules/server.main.iml
  .idea/modules/server.test.iml
  .idea/modules/user.iml
  .idea/modules/user.main.iml
  .idea/modules/user.test.iml
  .idea/modules/user/user/9pang.user.user.main.iml
Labels: bug

#51 Feature/delivery/crud
  common/src/main/java/com/_hateam/common/dto/PageResponseDto.java
  common/src/main/java/com/_hateam/common/exception/GlobalExceptionHandler.java
  delivery/src/main/java/com/_hateam/delivery/controller/DeliveryController.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/DeliveryResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/repository/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryService.java
Labels: enhancement

#56 Feature/message/order-status
  message/build.gradle
  message/src/main/java/com/_hateam/message/config/KafkaConfig.java
  message/src/main/java/com/_hateam/message/constant/KafkaTopics.java
  message/src/main/java/com/_hateam/message/event/DeliveryCreatedEvent.java
  message/src/main/java/com/_hateam/message/event/DeliveryStatusChangedEvent.java
  message/src/main/java/com/_hateam/message/event/OrderCreatedEvent.java
Labels: enhancement

#57 Feature/hubroute/manage
  .gitignore
  .idea/compiler.xml
  .idea/modules.xml
  common/build.gradle
  common/src/main/java/com/_hateam/common/aistudio/dto/GeminiRequestDto.java
  common/src/main/java/com/_hateam/common/redis/config/RedisConfig.java
  common/src/main/resources/application.properties
  eureka/build.gradle
  hub/hub/build.gradle
  hub/hub/src/main/java/com/_hateam/aistudio/GeminiService.java
  hub/hub/src/main/java/com/_hateam/aistudio/SendToAiMessage.java
  hub/hub/src/main/java/com/_hateam/aistudio/config/GeminiClientConfig.java
  hub/hub/src/main/java/com/_hateam/aistudio/controller/GeminiController.java
  hub/hub/src/main/java/com/_hateam/aistudio/dto/CreatedGeminiResponseDto.java
  hub/hub/src/main/java/com/_hateam/aistudio/dto/GeminiRequestDto.java
  hub/hub/src/main/java/com/_hateam/aistudio/dto/GeminiResponseDto.java
  hub/hub/src/main/java/com/_hateam/aistudio/entity/Gemini.java
  hub/hub/src/main/java/com/_hateam/aistudio/feign/GeminiClient.java
  hub/hub/src/main/java/com/_hateam/aistudio/repository/GeminiRepository.java
  hub/hub/src/main/java/com/_hateam/config/HubInitializer.java
  hub/hub/src/main/java/com/_hateam/dto/HubResponseDto.java
  hub/hub/src/main/java/com/_hateam/dto/HubRouteResponseDto.java
  hub/hub/src/main/java/com/_hateam/repository/HubRepository.java
  hub/hub/src/main/java/com/_hateam/service/GraphPathFinder.java
  hub/hub/src/main/java/com/_hateam/service/HubGraph.java
  hub/hub/src/main/resources/application.properties
Labels: enhancement

#65 Feature/delivery route/crud
  delivery/src/main/java/com/_hateam/delivery/controller/DeliveryController.java
  delivery/src/main/java/com/_hateam/delivery/controller/DeliveryRouteController.java
  delivery/src/main/java/com/_hateam/delivery/dto/request/UpdateDeliveryRequestDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/request/UpdateDeliveryRouteRequestDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/request/UpdateDeliveryStautsRequestDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/DeiiveryRouteResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/DeliveryResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/HubResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/entity/Delivery.java
  delivery/src/main/java/com/_hateam/delivery/entity/DeliveryRoute.java
  delivery/src/main/java/com/_hateam/delivery/repository/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/_hateam/delivery/repository/DeliveryRouteRepository.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryRouteService.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryService.java
Labels: enhancement

#78 Feature/delivery/feignclient
  delivery/Dockerfile
  delivery/build.gradle
  delivery/docker-compose-postgresql.yml
  delivery/docker-compose-redis.yml
  delivery/src/main/java/com/_hateam/delivery/DeliveryApplication.java
  delivery/src/main/java/com/_hateam/delivery/config/SecurityConfig.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/CompanyClientResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/DeiiveryRouteResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/DeliveryResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/HubClientHubResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/HubClientResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/OrderClientResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/UserClientDeliverResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/UserClientResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/entity/Delivery.java
  delivery/src/main/java/com/_hateam/delivery/entity/DeliveryRoute.java
  delivery/src/main/java/com/_hateam/delivery/feignClient/CompanyClient.java
  delivery/src/main/java/com/_hateam/delivery/feignClient/HubClient.java
  delivery/src/main/java/com/_hateam/delivery/feignClient/UserClient.java
  delivery/src/main/java/com/_hateam/delivery/repository/DeliveryRepositoryCustom.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryRouteService.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryService.java
  delivery/src/main/resources/application.properties
  eureka/settings.gradle
  user/user/src/main/java/com/_hateam/user/application/service/UserService.java
  user/user/src/main/java/com/_hateam/user/application/service/UserServiceImpl.java
  user/user/src/main/java/com/_hateam/user/presentation/controller/UserController.java
Labels: enhancement

#80 [feat] gateway의 security 인가기능 구현
  gateway/build.gradle
  gateway/src/main/java/com/_hateam/config/SecurityConfig.java
  gateway/src/main/java/com/_hateam/filter/CustomPostFilter.java
  gateway/src/main/java/com/_hateam/filter/CustomPreFilter.java
  gateway/src/main/java/com/_hateam/filter/JwtReactiveAuthenticationManager.java
  gateway/src/main/java/com/_hateam/filter/JwtSecurityContextRepository.java
  gateway/src/main/java/com/_hateam/filter/JwtUtil.java
  gateway/src/main/java/com/_hateam/filter/jwtAuthenticationFilter.java
  gateway/src/main/java/com/_hateam/gateway/GatewayApplication.java
  gateway/src/main/java/com/_hateam/testfilter/JwtAuthenticationFilter.java
  gateway/src/main/resources/application.properties
  gateway/src/main/resources/application.yml
  user/user/src/main/java/com/_hateam/user/application/service/UserService.java
  user/user/src/main/java/com/_hateam/user/application/service/UserServiceImpl.java
  user/user/src/main/java/com/_hateam/user/presentation/controller/UserController.java
Labels: enhancement

#83 Feature/feign/hub
  company/src/main/java/com/_hateam/config/CompanyInitializer.java
  company/src/main/java/com/_hateam/config/HubInitializer.java
  company/src/main/resources/application.properties
  eureka/src/main/resources/application.properties
  hub/hub/src/main/java/com/_hateam/config/CompanyInitializer.java
Labels: documentation

#93 [Feat] 배송 kafka 설정
  common/src/main/java/com/_hateam/common/event/DeliveryCreatedEvent.java
  common/src/main/java/com/_hateam/common/event/DeliveryStatusChangedEvent.java
  common/src/main/java/com/_hateam/common/event/KafkaEvent.java
  common/src/main/java/com/_hateam/common/event/OrderCreatedEvent.java
  delivery/build.gradle
  delivery/docker-dompose-kafka.yml
  delivery/src/main/java/com/_hateam/delivery/DeliveryApplication.java
  delivery/src/main/java/com/_hateam/delivery/config/ConsumerApplicationKafkaConfig.java
  delivery/src/main/java/com/_hateam/delivery/config/ProducerApplicationKafkaConfig.java
  delivery/src/main/java/com/_hateam/delivery/dto/response/OrderClientResponseDto.java
  delivery/src/main/java/com/_hateam/delivery/entity/Delivery.java
  delivery/src/main/java/com/_hateam/delivery/feignClient/UserClient.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryKafkaService.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryMessageConsumer.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryRouteService.java
  delivery/src/main/java/com/_hateam/delivery/service/DeliveryService.java
  delivery/src/main/resources/application.properties
Labels: enhancement

#96 fix : 요청시 401에러뜨는 문제 해결
  common/build.gradle
  common/src/main/java/com/_hateam/common/entity/Timestamped.java
  delivery/build.gradle
  hub/hub-route/build.gradle
  hub/hub/build.gradle
  order/build.gradle
  user/src/main/java/com/_hateam/user/presentation/controller/DeliverController.java
Labels: bug

#99 feat : zipkin(게이트웨이, 유저)에 추가, 유저 코드변경
  auth/src/main/java/com/_hateam/auth/application/dto/UserSignInResDto.java
  auth/src/main/java/com/_hateam/auth/application/service/AuthService.java
  docker-compose.yml
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  user/build.gradle
  user/src/main/java/com/_hateam/user/application/service/DeliverUserService.java
  user/src/main/java/com/_hateam/user/application/service/DeliverUserServiceImpl.java
  user/src/main/java/com/_hateam/user/application/service/UserService.java
  user/src/main/java/com/_hateam/user/application/service/UserServiceImpl.java
  user/src/main/java/com/_hateam/user/domain/enums/DeliverType.java
  user/src/main/java/com/_hateam/user/infrastructure/repository/DeliverUserRepositoryImpl.java
  user/src/main/java/com/_hateam/user/infrastructure/repository/JpaDeliverUserRepository.java
  user/src/main/java/com/_hateam/user/infrastructure/repository/UserRepositoryImpl.java
  user/src/main/java/com/_hateam/user/presentation/controller/DeliverController.java
  user/src/main/java/com/_hateam/user/presentation/controller/UserController.java
  user/src/main/resources/application.properties
Labels: enhancement

#101 Feature/message/feign-client
  delivery/src/main/java/com/_hateam/delivery/config/SecurityConfig.java
  docker-compose.yml
  gateway/src/main/resources/application.yml
  message/build.gradle
  message/docker-compose.yml
  message/src/main/java/com/_hateam/message/domain/repository/CompanyDeliveryRouteRepository.java
  message/src/main/java/com/_hateam/message/infrastructure/client/UserClient.java
  message/src/main/java/com/_hateam/message/infrastructure/messaging/OrderMessageConsumer.java
  message/src/main/java/com/_hateam/message/presentation/controller/SlackMessageController.java
  message/src/main/resources/application.properties
  order/docker-compose.yml
  order/src/main/java/com/_hateam/order/infrastructure/client/DeliveryClient.java
  order/src/main/java/com/_hateam/order/infrastructure/client/UserClient.java
  order/src/main/java/com/_hateam/order/infrastructure/config/SwaggerConfig.java
  order/src/main/resources/application.properties
Labels: bug, enhancement

#108 Feature/message/feign-client
  order/src/main/java/com/_hateam/order/application/dto/OrderRequestDto.java
  order/src/main/java/com/_hateam/order/infrastructure/client/CompanyClient.java
Labels: bug

#109 Feature/order/feign-client
  docker-compose.yml
  order/src/main/java/com/_hateam/order/application/service/OrderService.java
Labels: enhancement

#112 리프레시 토큰 구현
  auth/build.gradle
  auth/src/main/java/com/_hateam/auth/application/dto/FeignUserDto.java
  auth/src/main/java/com/_hateam/auth/application/dto/FeignVerifyResDto.java
  auth/src/main/java/com/_hateam/auth/application/dto/LogoutReqDto.java
  auth/src/main/java/com/_hateam/auth/application/dto/RefreshReqDto.java
  auth/src/main/java/com/_hateam/auth/application/dto/UserSignInResDto.java
  auth/src/main/java/com/_hateam/auth/application/service/AuthService.java
  auth/src/main/java/com/_hateam/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/_hateam/auth/domain/enums/UserRole.java
  auth/src/main/java/com/_hateam/auth/domain/model/RefreshToken.java
  auth/src/main/java/com/_hateam/auth/infrastructure/config/JwtUtil.java
  auth/src/main/java/com/_hateam/auth/infrastructure/config/RedisConfig.java
  auth/src/main/java/com/_hateam/auth/infrastructure/exception/AuthException.java
  auth/src/main/java/com/_hateam/auth/infrastructure/exception/GlobalExceptionHandler.java
  auth/src/main/java/com/_hateam/auth/infrastructure/feign/UserClient.java
  auth/src/main/java/com/_hateam/auth/infrastructure/repository/RefreshTokenRepository.java
  auth/src/main/java/com/_hateam/auth/presentation/controller/AuthController.java
  auth/src/main/resources/application.properties
  common/build.gradle
  gateway/src/main/java/com/_hateam/gateway/domain/enums/UserRole.java
  gateway/src/main/java/com/_hateam/gateway/infrastructure/config/SecurityConfig.java
  gateway/src/main/java/com/_hateam/gateway/infrastructure/config/WebConfig.java
  gateway/src/main/java/com/_hateam/gateway/infrastructure/exception/GlobalErrorWebExceptionHandler.java
  gateway/src/main/java/com/_hateam/gateway/infrastructure/filter/JwtAuthenticationFilter.java
  gateway/src/main/java/com/_hateam/gateway/infrastructure/filter/JwtReactiveAuthenticationManager.java
  gateway/src/main/java/com/_hateam/gateway/infrastructure/filter/JwtSecurityContextRepository.java
  user/src/main/java/com/_hateam/user/application/service/UserServiceImpl.java
  user/src/main/java/com/_hateam/user/infrastructure/feign/AuthClient.java
  user/src/main/java/com/_hateam/user/infrastructure/repository/JpaDeliverUserRepository.java
Labels: documentation
